### ISSUE TITLE
pdf file download

### ISSUE THREAD

**Issue by paulomartinspt** [KD4Z/md380tools-vm#1]
The file says: Sorry, this file is invalid so it cannot be displayed.

Great work on the VM mate!
Regards,
Paulo CS7AGH

**Comment by KD4Z** [comment]
Hi Paulo,
Are you having trouble opening the pdf on github?  I'll attach the
original for you.  Let me know if you still can't open it.

73 de KD4Z

**Comment by paulomartinspt** [comment]
Hi
Yes, if i download or try to see it on GitHub it gives that message
I thought it was strange that he had only a few kb of size

Thanks!

**Comment by paulomartinspt** [comment]
It worked!
Now it shows 485 KB. In the afternoon it only showed like 43KB and i couldn't see or download it.
