### ISSUE TITLE
Running on UBUNTU 16.x 

### ISSUE THREAD

**Issue by iw9grl** [KD4Z/md380tools-vm#10]
"flash" command  : Errno 13 Access denied ( insufficient permission )

73

**Comment by KD4Z** [comment]
Did you run this command as specifed in the md380tools readme?

cd md380tools
sudo cp 99-md380.rules /etc/udev/rules.d/


\On 2/21/2017 6:04 PM, iw9grl wrote:

**Comment by iw9grl** [comment]
Thank you , now it works !!!!!!!!!!!!!!!!!!!!


73 de IW9GRL

**Comment by KD4Z** [comment]
Fantastic!  Enjoy.
