### ISSUE TITLE
Wrong keyboard layout in VM

### ISSUE THREAD

**Issue by mike6000** [KD4Z/md380tools-vm#12]
I have a scandinavian keyboard layout. When booting your VM, I cannot type equal sign, slash etc. Since I am not root (and dont have the root password) I cannot edit /etc/default/keyboard. 

Can you inform about the root password in your VM Linux image so we can edit keyboard layout pse. 
Also, what distro of of linux is it? 

73

**Comment by KD4Z** [comment]
Send me a private email at my QRZ address and I'll send you the root
password.

**Comment by mike6000** [comment]
QSL will do
