### ISSUE TITLE
Bug found in building the users database

### ISSUE THREAD

**Issue by jdrago** [KD4Z/md380tools-vm#13]
Hi Warren,

The 'user.bin' file is getting munged-up anytime a static.users file is included.

I first noticed the issue when I created one entry in the static.users file using this format (101,call1,name1,city1,state1,nickname1,country1) .  The actual entry is:
3139370,W8FAA,John,Atwater,OH,John,USA
When the database is created, I do a lookup on the callsign with ./lookup W8FAA.  Lookup returns two results.  The first is my record as shown above.  The second is (at the time of this post) a record for call CX1RK.  This second record is the record for CX1RK from the database, but it has my record concatenated to the end of it.

SO, I removed my record from static.users and re-ran 'glvusers'.  The user.bin file is still corrupt in the same place, but with different data.  Something is wrong in the process that merges the data together.

**Edit: Looks like CX1RK is the last entry in the original user.bin file.  The issue is the addstatic script may not be adding a LF before inserting the static.users file.**

73,
John W8FAA
john.drago@mac.com

**Comment by PD0DIB** [comment]
Hi John,
Is it possible the "old" entry is from before mid December 2016?

That's the period Warren did a store of the MARC database before MARC
decided to filter the database extraction; I.e. did not included name and
address info anymore.

That stored 'froozen' file with the full dataset is always added when you
execute a glv or glvusers to make the database as complete as possible (as
in the 'old' days).
So it is not a bug, it is a non documented feature.
73 de PD0DIB

Op 26 mrt. 2017 9:45 p.m. schreef "John Drago" <notifications@github.com>:

**Comment by KD4Z** [comment]
John, 
glv now and see if you have the same issue.  After glv, you can go back to glvusers again.  The seed file, the static.users file, and the dmr-marc.tmp file get appended together and there needed to be a line break added after the seed file.  CX1RX happens to be the last entry in the seed file.

**Comment by jdrago** [comment]
Yes, the issue looks like it is corrected.  However, FYI, there is a blank entry (,,,,,,) in line 2 of the user.bin file after the ‘glv’.  Thank you,

73,
John

**Comment by KD4Z** [comment]
blank line removed.
