### ISSUE TITLE
Data format - Talker Alias

### ISSUE THREAD

**Issue by pjao** [KD4Z/md380tools-vm#15]
Hi there!

It looks after the last change on the md380tools, if you want on the submenu: "Date format" use the new option "TalkerAlias" it doesn't work.

Tried with the base md380tools by travisgoodspeed and it works.

Paulo - CT2JAY

**Comment by pjao** [comment]
Nice updates!

https://github.com/KD4Z/md380tools-vm/commit/0be89e274fae07e4afaffa097d364131ba271da7

https://github.com/KD4Z/md380tools-vm/commit/82c45dc2d3d8d1ac62ca15150b2acc57a1ebaf7f

Still missing "Date format" - "Talker Alias"

**Comment by KD4Z** [comment]
I'll look again, but don't think my custom display affects that
option...Maybe buried in there ;)

**Comment by KD4Z** [comment]
GLV and Flash now Paulo... I just posted Test #3, which brings in the Date Format for Talker alias.

**Comment by pjao** [comment]
@KD4Z Working very nice! 

Good job! 

For now I think we can close this issue introduced by md380tools. 

You display is 5*

**Comment by KD4Z** [comment]
Ok, will do.  I'm still working on this...I always like to tweak stuff in the UI.   It will get better as time permits!
