### ISSUE TITLE
Red button bug.

### ISSUE THREAD

**Issue by PD1LOI** [KD4Z/md380tools-vm#16]
When I press 2X red, I have a light blue blank screen with analogue transmitter. Then I press green, I see the normal menu, I press red again, and it will hold everything.
In my opinion, I'm still a bug.

**Comment by KD4Z** [comment]
Loui,
Wolf needs this kind of feedback since he is still working on this area of the code.   Since it is really in the main code line of md380tools, it would be best to make a post on the Google group here:

https://groups.google.com/forum/#!forum/md380tools
