### ISSUE TITLE
Error in seed.bin

### ISSUE THREAD

**Issue by PD1LOI** [KD4Z/md380tools-vm#17]
Warren can you customize in Seed.bin? There is a mistake.
2042307, PE1ORP, Andre Stellindga, Spijkernisse, South Holland, Andre, Netherlands
Must be
2042307, PE1ORP, Andre Jacob Witte, Spijkernisse, South Holland, Andre, Netherlands

**Comment by KD4Z** [comment]
Sorry, I missed this until now.  Seed data updated.
