### ISSUE TITLE
Demo Screen not enable.

### ISSUE THREAD

**Issue by PD1LOI** [KD4Z/md380tools-vm#19]
Menu, MD380Tools, Display, Boot Option, Demo Screen is on Disable and I can not set to Enable. is this known?

**Comment by KD4Z** [comment]
A pull request was merged that fixes the display options in the menu for mic bargraph, roger-beep,  Experimental, and promiscuous modes.  They were being configured opposite of the selected setting.   Try a new build of firmware now and see if your items also got fixed.  If not, it will be easy to fix them as well.

**Comment by PD1LOI** [comment]
No, still the same problem. You can not choose whether or not the setting will always be the same.

**Comment by KD4Z** [comment]
I can not reproduce this issue in current builds.  It would be something addressed up-stream in Travis: master anyway.  Closing.
