### ISSUE TITLE
Enable bash history

### ISSUE THREAD

**Issue by b4d** [KD4Z/md380tools-vm#27]
Hi, in earlier version, bash history was saved, that is useful so people can search or arrow up the old commands quickly. Any way to bring that back?

**Comment by b4d** [comment]
I just checked at my other computer and go figure, it works here... Will look into it.

**Comment by KD4Z** [comment]
Perhaps you were logged in as a different user or su'd to root?   Nothing special about history is changed in the VM.   You can look at the .bash_history file to see what is there.

**Comment by b4d** [comment]
Yeah, I am planning to check it when I come home, still at work :D
