### ISSUE TITLE
Download user.csv to pc.

### ISSUE THREAD

**Issue by PD1LOI** [KD4Z/md380tools-vm#3]
It is also possible to download these user.csv stripped.csv on your PC?

**Comment by KD4Z** [comment]
If I understand your question correctly, the user.bin file can be used on another pc, if you have the md380tools installed to install it in the radio.  You can't use the TYT CPS program to install it on to the radio.   You can use the "ftp" command inside the VM to copy it out, but you will need an ftp server somewhere to receive it.  The user.bin is located in the home folder for tyt in the VM after a glv command.  If you do a dir command, you should see it.

**Comment by KD4Z** [comment]
A feature has just been added in 3.06 to support automatic static.users file download from an ftp server.  If you create a static.host file, containing the fully qualified URL to the your desired "static file" on an ftp server somewhere, it will be downloaded at glv time.  See the new document version 3.06 for a bit more information.

**Comment by KD4Z** [comment]
Closing ticket.  I believe this is no longer an issue as the documentation has been updated to describe how to do this.
