### ISSUE TITLE
Error during GLV: Certificate not found

### ISSUE THREAD

**Issue by ctucker1984** [KD4Z/md380tools-vm#30]
![tyt error](https://user-images.githubusercontent.com/17303051/42545360-47a5fa10-846c-11e8-85ba-aeba47452e86.JPG)

I get this when running glv. I can't identify how to resolve it. This is a Virtual Box installation.

**Comment by KD4Z** [comment]
Try re-importing the OVA to recreate the VM.   Something has been corrupted.  The certificate for github appears to be valid and is git clone is working in the VM.

**Comment by ctucker1984** [comment]
I actually did that from a fresh download of the program. Still no luck.

**Comment by KD4Z** [comment]
Does the VM seem to have good internet connectivity?  Can you ping addresses on the Net?
`ping www.google.com`   
Ctrl+C to exit from ping.   If you got replies, that is good.  If you got lost packets, work on getting the VM to have a working network adapter.  See the FAQ in the Facebook Group for hints.

**Comment by ctucker1984** [comment]
I tore the whole thing down and reinstalled VBox and your VM. It’s working now. Thanks. 

- Chris Tucker

**Comment by KD4Z** [comment]
Ok, great!
