### ISSUE TITLE
missing closing " on line 25

### ISSUE THREAD

**Issue by javastraat** [KD4Z/md380tools-vm#32]
bash_aliases generates error when logging in 

-bash: /home/pi-star/.bash_aliases: line 36: unexpected EOF while looking for matching `"'
-bash: /home/pi-star/.bash_aliases: line 46: syntax error: unexpected end of file

add " and it will work again

**Comment by KD4Z** [comment]
Crap.  Thanks,  I missed that..  I'll fix it now.
