### ISSUE TITLE
user db not uploading to radio

### ISSUE THREAD

**Issue by worsthorse** [KD4Z/md380tools-vm#34]

**Comment by worsthorse** [comment]
I installed the latest version of VirtualBox, the extension pack, and the VM machine (V4.04). I had MD380toolz running on my radio, so I  flashed back to the TYT D13.34 firmware.  The virtual machine starts up as expected. I run glv, then flash and the radio is flashed to MD380 tools. The "welcome" screen shows 2.15.19 as the install date and 3ffa43f as the "version" code. All functionality seems to work as expected.  

I then run flashdb.  I see the expected stuff... the dbase gets built. the flash process says "spi flash id ef 40 18" and sees that the radio has 16MB of flash, the erase "happens" in ten percent chunks, the write "happens" in ten percent chunks. I get the expected final message.  So all seems well.

I have "TA and UserDB" turned on in Show Calls. No joy... 

The original 53 contacts that were in the radio before are still there. No new contacts are visible. 

One thing I noticed: the erase and write cycles seemed to go by more quickly than I expected. Less than three minutes to erase or write. 

I tried deleting the various downloaded user files from the virtual machine, including user.bin and rebuilding the contact database from scratch. Same result. I checked the user.bin file and it contains contact info, as expected.

Any ideas?

**Comment by worsthorse** [comment]
One additional piece of data. When I use "parrot" to test the radio, the caller id comes up unknown on the return call, with a note to run glvuser and then flashdb.

**Comment by KD4Z** [comment]
You need to check that you have the radio configured to use the extra contact data.  It doesn't write the contacts into the "codeplug area" , so you will never see them in the stock screen for contacts.   Go to Utilities/MD380Tools/Display / Show Calls and change the option to User DB.   This is not a bug.

**Comment by worsthorse** [comment]
As I noted in my original post, I set "TA and Userdb" turned on in "Show Call".  I also tried "Userdb". I tried both settings before I posted my report. I get the same result each time, which is contacts are appearing  as unknown and the same screen displays a message which says to run glvdb and flashdb.  What does the error message actually mean?

And... is there any way to read back the flash memory and check to see if the contact list has actually been flashed?

**Comment by KD4Z** [comment]
Did you run flashdb with the radio in DFU mode?    Don't.   DFU mode only for the flash command.  Just turn the radio on for flashdb.  I believe the Toolkit reminds you to do this.   There is a way to dump the SPI flash data to a file, and then you can look to see the user data starting at the 1 Meg boundary going up from there for about 6 Megs.    I've documented the steps to extract the image from the radio in this thread here:  
https://www.facebook.com/groups/KD4ZToolkit/permalink/310126322830331/?hc_location=ufi

Grab full spi flash space to file:

python ~/md380tools/md380-tool spiflashdump mydump.bin

Then strip off first 1 Meg and export for 6 megs worth as the contacts start there.

dd if="./mydump.bin of=./mychunk.bin skip=1 count=6 ibs=1M obs=1M

mychunk.bin will be the file you want to look at.

**Comment by worsthorse** [comment]
I ran flashdb with the radio in normal operating mode (the "pc usb programming" screen appears as expected) not in DFU mode. 

Thanks for the pointer. I will grab the SPI flash file and see if the data is there. I appreciate the help.

**Comment by KD4Z** [comment]
@wch-k7wxw Are you still having issues getting the DB data to display?  Did you figure out that the User DB download does not add "Contacts" into the stock firmware's Contacts area?  I'd like to close this issue if you are good to go.

**Comment by worsthorse** [comment]
Sorry that I missed your request to close. Yup. I followed the instructions as written and I am seeing contact information as expected. You can close this

**Comment by namtsuy** [comment]
> You need to check that you have the radio configured to use the extra contact data. It doesn't write the contacts into the "codeplug area" , so you will never see them in the stock screen for contacts. Go to Utilities/MD380Tools/Display / Show Calls and change the option to User DB. This is not a bug.

Nicely done, thank you for the advice.  WV6S, Robert.  It worked !!!
