### ISSUE TITLE
Database not correct this morning.

### ISSUE THREAD

**Issue by PD1LOI** [KD4Z/md380tools-vm#4]
Database is not complete, still yesterday.
![img_20170111_114728](https://cloud.githubusercontent.com/assets/2943825/21845841/9722ed76-d7f4-11e6-8d72-7c146da41fe5.jpg)

Yesterday 
![15965949_1503842066311513_1478073508549664049_n](https://cloud.githubusercontent.com/assets/2943825/21845894/d273d502-d7f4-11e6-876f-9fa3b41e35fc.jpg)

**Comment by KD4Z** [comment]
Closing ticket.  I believe this is no longer an issue
