### ISSUE TITLE
User.bin copy to home server.

### ISSUE THREAD

**Issue by PD1LOI** [KD4Z/md380tools-vm#7]
It is not an error but a sugestie.
Is it possible to user.bin file using the menu command to write to the server? there are namely the new users in. So we can customize this file and then rename it to static.users.txt.

greetings PD1LOI

**Comment by KD4Z** [comment]
You can do that right now yourself.   Create a bash script called exec.post.local in the home directory.  Anything in that script will automatically be run at the end of glv or glvusers.   It needs to have a "shebang" as the first line.

#!/bin/bash

Then, use whatever command you want like ftp, to copy the users.bin out to an external server.

This is one of three scripts that you can use to hook into the system at various points.   exec.pre.local is called right before compiling starts.   exec.post.local is the last thing called before returning to the prompt after glv/glvusers.

**Comment by PD1LOI** [comment]
Can you make this script? the server folder where static.user.txt able = 
D: \ Toolkit


Op 7-2-2017 om 13:36 schreef KD4Z:
>
> Create a bash script called exec.post.local in the home directory. 
> Anything in that script will automatically be run at the end of glv or 
> glvusers. It needs to have a "shebang" as the first line.
>
> #!/bin/bash
>
> Then, use whatever command you want like ftp, to copy the users.bin 
> out to an external server.
>
> This is one of three scripts that you can use to hook into the system 
> at various points. exec.pre.local is called right before compiling 
> starts. exec.post.local is the last thing called before returning to 
> the prompt after glv/glvusers.
>

**Comment by KD4Z** [comment]
I have already created a sample upload script for everyone.  It is located in the home directory and is called "uploadfile"   Take a look at it.  Change the required information to suit your server.    I created that script as a sample to do just what you are asking...

**Comment by PD1LOI** [comment]
I'm awkward, but my intention was that the merged user.bin so could be downloaded along with static.users.txt. further only works if I so manually upload file starts I get continuously to the end END run.

**Comment by PD1LOI** [comment]
I have asked usr.bin can be downloaded, but I've already arranged for myself.
![virtualbox_tyt_08_02_2017_11_48_37](https://cloud.githubusercontent.com/assets/2943825/22734355/b146cab2-edf5-11e6-92f7-687e9a2d5d7c.png)

**Comment by KD4Z** [comment]
That looks correct Loui.   I'll try to reproduce it here.   The only thing might be the upload folder on your server might not need the prefix of /    You could try:  uploadfolder="Toolkit"

You should try manually connecting to your ftp server from the linux prompt to check it out.

ftp -p ipaddress

enter your user and password

cd Toolkit

put user.bin

quit

--
If that works, change the script to have uploadfolder="Toolkit"

**Comment by PD1LOI** [comment]
![virtualbox_tyt_10_02_2017_14_59_06](https://cloud.githubusercontent.com/assets/2943825/22829251/f6ee9592-efa1-11e6-8e2c-33861020982e.png)
This is what I see. And he does not stop at the end, I have to close the program or it does not stop.

And this is my upload file:
#/bin/bash

# uploadfile.sample script
# KD4Z
# Version:  3.07
#
# upload a file from a given directory
# to an ftp server outside the VM

# First, rename this to uploadfile!
#
# you can execute this manually at the prompt with
#
#   ~/uploadfile
#
# or you can create a script called exec.post.local and it will get
# called automatically at the end of the glv or glvusers
#
#   nano ~/exec.post.local
#
# with this content


#    #/bin/bash
#   ~/uploadfile



###########################################################################
# Settings to change.  You must configure these for your server
###########################################################################

host=192.168.2.9
user=ftpuser
pass=lk000

# this is the folder to upload the file to on the ftp server
# leave as "/" if your file is to go into the default folder for the user
# or if you want to change to a folder named "my/data"  (it must already exist on the server) 
# set uploadfolder="/my/data"
# 
uploadfolder="/Toolkit"


# change these if you need a different file uploaded

file="user.bin"
localfolder="~/home/tyt"

###########################################################################
# You don't need to change anything below this line
###########################################################################

echo -e "${GREEN}Uploading ${file} to local ftp server at ${host}${NC}"

ftp -p -n <<EOF
open ${host}
user ${user} ${pass}
lcd "${localfolder}"
cd "${uploadfolder}"
put "${file}"
EOF

echo -e "${GREEN}Upload complete${NC}"

**Comment by PD1LOI** [comment]
Everything works well here now. may it be closed to me.

**Comment by KD4Z** [comment]
Thank you Loui.
