### ISSUE TITLE
Dmr user 2x listed with the same ID.

### ISSUE THREAD

**Issue by PD1LOI** [KD4Z/md380tools-vm#9]
Warren fetching user.bin I come every time this person at 2x.
2043138 PD2DL Dirk Loenen, Utrecht, Utrecht, Dirk, Netherlands
2043138, PD2DL Dirk,,,, Netherlands

Is to adapt this?

**Comment by KD4Z** [comment]
Loui, is one of those lines actually missing a comma?  If so, they look like two distinct records to the duplicate reducer   Check your external 'stripped.csv' file for the records.  I think they may be coming from that. I checked the seed file and it's not there :)

**Comment by PD1LOI** [comment]
2043138 PD2DL
2043138, PD2DL That was the problem.
May be closed.

**Comment by KD4Z** [comment]
Excellent!
